language: python
python:
  - 3.6.4
env:
  - docker_name=docker-test
services:
  - docker
install:
  - docker build -t $docker_name .
  - docker run -d -p 5000:5000 $docker_name
before_script:
  - pip install pytest
  - pip install requests
script:
  - docker ps | grep -q $docker_name
  - pytest test.py
