version: "3"

services:
  dockertest:
    image: docker_test
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 5000:5000
    networks:
      - my-bridge
  redis:
    image: my_redis
    build:
      context: ./redis
    volumes:
      - ./redis/redis_data:/data
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge
