version: "3"

services:
  dockertest:
    image: dockertest
    build: ./app
    ports:
      - 5000:5000
    networks:
      - my-bridge
  redis:
    image: redis
    build: ./redis
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
      - ./redis/redis_data:/data
    command:
      - redis-server
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge
