version: "3"

services:
  dockertest:
    image: dockertest
    build: .
    ports:
      - 5000:5000
    # depends_on:
    # - redis
    networks:
      - my-bridge

  redis:
    image: redis
    volumes:
      - redis-data:/var/data
    networks:
      - my-bridge

volumes:
  redis-data:

networks:
  my-bridge:
    driver: bridge
